services:
  mongodb:
    image: 'mongodb/mongodb-community-server:latest'
    ports:
      - "27017:27017"

  backend:
    build: ./backend/
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ~/.ssl:~/.ssl
