services:
  mongodb:
    image: 'mongodb/mongodb-community-server:latest'
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    profiles:
      - prod
      - local
      
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    profiles:
      - prod
      - local

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=https://wg84a.at
    profiles:
      - prod

  frontend-local:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=http://localhost
    profiles:
      - local

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - /etc/ssl:/etc/ssl
    profiles:
      - prod

  nginx-local:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/local:/etc/nginx/conf.d
    profiles:
      - local

volumes:
  mongodb_data_container:
