name: 'update wg-bier-manager'

on:
  push:
    branches: [main]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Core2Goal/ssh-action@v1
        with:
          host: ${{ secrets.SSH_DOMAIN }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd wg-bier-manager/ &&
            git pull &&
            ./run.sh --prod
